# Generated by Django 2.2.1 on 2020-02-02 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('think', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=150, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='think',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='thinks', to='think.Tag'),
        ),
    ]
